/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unicro.view;

import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import unicro.entity.Voucher;
import unicro.service.Voucher_Service;

/**
 *
 * @author Admin
 */
public class KhuyenMai extends javax.swing.JPanel {
 private DefaultTableModel model;
    List<Voucher> list = new ArrayList<>();
    private Voucher_Service service = new Voucher_Service();
    /**
     * Creates new form KhuyenMai
     */
    public KhuyenMai() {
        initComponents();
         cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Đang hoạt động", "Không hoạt động"}));
        fillTable();
        
//         setLayout(new BorderLayout()); // hoặc GridBagLayout nếu cần căn chỉnh nâng cao
//
//        JPanel content = new JPanel();
//        content.setLayout(new GridBagLayout()); // Căn giữa
//
//        JLabel label = new JLabel("Quản lý Voucher");
//        content.add(label);
//
//        add(content, BorderLayout.NORTH); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNgayBd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        txtNgayKt = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaVoucher = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        txtGiamGia1 = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        txtGiamGia2 = new javax.swing.JTextField();

        jLabel5.setText("Ngày BĐ(yyyy-mm-dd) :");

        jLabel6.setText("Ngày KT(yyyy-mm-dd) :");

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Giảm giá theo", "Giá trị giảm", "Ngày bắt đầu", "Ngày kết thúc", "Ngày tạo", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã voucher :");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel3.setText("Giảm giá theo :");

        btnXoa.setText("Xoá");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel4.setText("Giá trị giảm");

        jLabel7.setText("Trạng thái :");

        txtMaVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaVoucherActionPerformed(evt);
            }
        });

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        txtGiamGia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiamGia2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnThem)
                                .addGap(100, 100, 100)
                                .addComponent(btnSua))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiamGia2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtMaVoucher)
                                    .addComponent(txtGiamGia1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayBd, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(btnXoa)
                                .addGap(88, 88, 88)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnReset, btnSua, btnThem, btnXoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGiamGia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiamGia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnReset, btnSua, btnThem, btnXoa});

    }// </editor-fold>//GEN-END:initComponents

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        int selectedRow = tblVoucher.getSelectedRow();
        if (selectedRow >= 0) {
            txtMaVoucher.setText(tblVoucher.getValueAt(selectedRow, 0).toString());
            txtGiamGia1.setText(tblVoucher.getValueAt(selectedRow, 1).toString());
            txtGiamGia2.setText(tblVoucher.getValueAt(selectedRow, 2).toString());
            txtNgayBd.setText(tblVoucher.getValueAt(selectedRow, 3).toString());
            txtNgayKt.setText(tblVoucher.getValueAt(selectedRow, 4).toString());
            String trangThai = tblVoucher.getValueAt(selectedRow, 6).toString();
            if (trangThai.equalsIgnoreCase("Đang hoạt động")) {
                cboTrangThai.setSelectedItem("Đang hoạt động");
            } else {
                cboTrangThai.setSelectedItem("Không hoạt động");
            }
        }
    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            String code = txtMaVoucher.getText().trim();
            String discountType = txtGiamGia1.getText().trim();
            BigDecimal discountValue = new BigDecimal(txtGiamGia2.getText().trim());
            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-M-d");
            String ngayBdRaw = txtNgayBd.getText().trim();
            String ngayKtRaw = txtNgayKt.getText().trim();
            LocalDate startLocalDate = LocalDate.parse(ngayBdRaw, dateFormatter);
            LocalDate endLocalDate = LocalDate.parse(ngayKtRaw, dateFormatter);
            LocalDateTime createdAt = LocalDateTime.now();
            boolean isActive = cboTrangThai.getSelectedItem().toString().equals("Đang hoạt động");
            Voucher v = new Voucher();
            v.setCode(code);
            v.setDiscount_type(discountType);
            v.setDiscount_value(discountValue);
            v.setStart_date(startLocalDate);
            v.setEnd_date(endLocalDate);
            v.setCreated_at(createdAt);
            v.setActive(isActive);
            boolean success = service.addVoucher(v);
            if (success) {
                JOptionPane.showMessageDialog(this, "Thêm thành công!");
                fillTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            String code = txtMaVoucher.getText().trim();
            String discountType = txtGiamGia1.getText().trim();
            BigDecimal discountValue = new BigDecimal(txtGiamGia2.getText().trim());
            DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-M-d");
            String ngayBdRaw = txtNgayBd.getText().trim();
            String ngayKtRaw = txtNgayKt.getText().trim();
            LocalDate startLocalDate = LocalDate.parse(ngayBdRaw, dateFormatter);
            LocalDate endLocalDate = LocalDate.parse(ngayKtRaw, dateFormatter);
            LocalDateTime createdAt = LocalDateTime.now();
            boolean active = cboTrangThai.getSelectedIndex() == 0;
            Voucher v = new Voucher();
            v.setCode(code);
            v.setDiscount_type(discountType);
            v.setDiscount_value(discountValue);
            v.setStart_date(startLocalDate);
            v.setEnd_date(endLocalDate);
            v.setCreated_at(createdAt);
            v.setActive(active);
            boolean result = service.updateVoucher(v);
            if (result) {
                JOptionPane.showMessageDialog(this, "Cập nhật voucher thành công!");
                fillTable();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật voucher thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        try {
            String code = txtMaVoucher.getText().trim();
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xoá voucher này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                boolean result = service.deleteVoucher(code);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Xoá voucher thành công!");
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xoá voucher thất bại!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtMaVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaVoucherActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaVoucher.setText("");
        txtGiamGia1.setText("");
        txtGiamGia2.setText("");
        txtNgayBd.setText("");
        txtNgayKt.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtGiamGia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiamGia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiamGia2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField txtGiamGia1;
    private javax.swing.JTextField txtGiamGia2;
    private javax.swing.JTextField txtMaVoucher;
    private javax.swing.JTextField txtNgayBd;
    private javax.swing.JTextField txtNgayKt;
    // End of variables declaration//GEN-END:variables
 public void fillTable() {
        model = (DefaultTableModel) tblVoucher.getModel();
        model.setRowCount(0);
        list = service.getAllVouchers();
        for (Voucher v : list) {
            model.addRow(new Object[]{
                v.getCode(),
                v.getDiscount_type(),
                v.getDiscount_value(),
                v.getStart_date(),
                v.getEnd_date(),
                v.getCreated_at(),
                v.getActive() ? "Đang hoạt động" : "Ngưng hoạt đông"
            });
        }
    }
}
