/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unicro.view;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import unicro.view.KhuyenMai;

/**
 *
 * @author Admin
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    private JPanel mainPanel;
    private CardLayout cardLayout;

    public TrangChu() {
        initComponents();
        setTitle("Phần mềm quản lý bán hàng");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1000, 600);
        setLocationRelativeTo(null);

        // ===== MENU PANEL (Top Buttons) =====
        JPanel menuPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        menuPanel.setBackground(Color.WHITE);
        menuPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // padding

        // Font & màu
        Font menuFont = new Font("Segoe UI", Font.PLAIN, 14);
        Color btnColor = new Color(52, 152, 219);
        Color btnText = Color.WHITE;

        // Tạo các button menu
        String[] menuNames = {"Bán Hàng", "Quản lý sản phẩm", "Thống kê", "Khuyến mãi", "Người dùng"};
        JButton[] menuButtons = new JButton[menuNames.length];
        for (int i = 0; i < menuNames.length; i++) {
            JButton btn = new JButton(menuNames[i]);
            btn.setFocusPainted(false);
            btn.setFont(menuFont);
            btn.setBackground(btnColor);
            btn.setForeground(btnText);
            btn.setPreferredSize(new Dimension(160, 35));
            menuButtons[i] = btn;
            menuPanel.add(btn);
        }

        // ===== MAIN PANEL (CardLayout) =====
        cardLayout = new CardLayout();
        mainPanel = new JPanel(cardLayout);

        // ⚠️ Đảm bảo các class sau là JPanel, không phải JFrame!
        mainPanel.add(new BanHang(), "BanHang");
        // mainPanel.add(new SanPhamPanel(), "QLSP"); // nhớ tạo class JPanel
        mainPanel.add(new ThongKe(), "ThongKe");
        mainPanel.add(new KhuyenMai(), "KhuyenMai");
        mainPanel.add(new NguoiDung(), "NguoiDung");

        // ===== GÁN SỰ KIỆN MENU =====
        menuButtons[0].addActionListener(e -> cardLayout.show(mainPanel, "BanHang"));
        menuButtons[1].addActionListener(e -> cardLayout.show(mainPanel, "QLSP"));
        menuButtons[2].addActionListener(e -> cardLayout.show(mainPanel, "ThongKe"));
        menuButtons[3].addActionListener(e -> cardLayout.show(mainPanel, "KhuyenMai"));
        menuButtons[4].addActionListener(e -> cardLayout.show(mainPanel, "NguoiDung"));

        // ===== HEADER + MENU COMBO =====
        JLabel titleLabel = new JLabel("PHẦN MỀM QUẢN LÝ BÁN HÀNG", JLabel.CENTER);
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 20));
        titleLabel.setForeground(new Color(41, 128, 185));

        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.add(titleLabel, BorderLayout.NORTH);
        headerPanel.add(menuPanel, BorderLayout.SOUTH);
        headerPanel.setBackground(Color.WHITE);

        // ===== SETUP FRAME =====
        setLayout(new BorderLayout());
        add(headerPanel, BorderLayout.NORTH);
        add(mainPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // Chạy ứng dụng
        EventQueue.invokeLater(() -> new TrangChu().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
